### ISSUE TITLE
issue uploading skill code to lambda

### ISSUE THREAD

**Issue by MisterFili** [alexa/interactive-adventure-game-tool#18]
Anytime i hit the save button to send my code to lambda i'm receiving the below error. Any leads into what could be causing this? I've recreated my roles with admin access and update my credential file, no luck. 

`/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:30
            throw err;
            ^

Error: Missing credentials in config
    at Request.callListeners (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interactive-adventure-game-tool@1.0.0 start script 'node node_modules/gulp/bin/gulp.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the interactive-adventure-game-tool package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/gulp/bin/gulp.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs interactive-adventure-game-tool
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls interactive-adventure-game-tool
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MisterFili/Documents/InteractiveStory/interactive-adventure-game-tool/npm-debug.log`

**Comment by MisterFili** [comment]
The error clearly states "Error: Missing credentials in config" and needed to update my config file. it is a good idea to step away from work if you are tired or frustrated.

**Comment by SirNeuton** [comment]
What exactly did you do? Got the same error but can't figure out how to fix it... keys in the credentials file in .aws should be alright so I'm pretty confused atm

**Comment by nimzoking** [comment]
I have a similar issue, mine says the User is not authorised to perform lambda:UpdateFunctionCode - I have checked the user and their permissions, and they should be able to access.  

So off to check and review the code once again :)

I am running on Linux rather than a Mac - but the shell should be very similar.....

Mind you, I guess I have not too bad on AWS with just 4 hours use of AWS going through various tutorials.  I am using the deprecated package - so I am wondering if that could be one behind the reason if AWS have changed things in the console.

**Comment by nimzoking** [comment]
LOL - a typo!  The arn string had one digit that was wrong, a '4' instead of a '7' ..

Yes, cut&paste helps if you have access to the command, but as I am running Linux in a VM on Windows, and doing all the AWS stuff on my Windows web and running the code on the Linux VM then I guess typo's like this are inevitable .... 

So it works, so far.... upload as works and the "save" has generated the files in the "model" directory on the Linux VM.

Really cool example 👍
