### ISSUE TITLE
Can't Upload!! :(

### ISSUE THREAD

**Issue by talk2camden** [alexa/interactive-adventure-game-tool#37]
**Here's my code:**

```
[13:19:39] Starting 'generate'...
[13:19:39] Finished 'generate' after 6.89 ms
[13:19:39] Starting 'upload'...
[13:19:40] Uploading Lambda function "InteractiveStoryLambdaFunction"...
C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\request.js:30
            throw err;
            ^

Error: Missing credentials in config
    at Request.callListeners (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\sequential_executor.js:107:43)
    at Request.emit (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\request.js:596:14)
    at Request.transition (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\request.js:21:10)
    at AcceptorStateMachine.runTo (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\request.js:37:9)
    at Request.<anonymous> (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\request.js:598:12)
    at Request.callListeners (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (C:\Users\camde\Documents\GitHub\interactive-adventure-game-tool\node_modules\gulp-awslambda\node_modules\aws-sdk\lib\sequential_executor.js:77:10)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\camde\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the interactive-adventure-game-tool@1.0.0 start script 'node node_modules/gulp/bin/gulp.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the interactive-adventure-game-tool package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/gulp/bin/gulp.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs interactive-adventure-game-tool
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls interactive-adventure-game-tool
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\camde\AppData\Roaming\npm-cache\_logs\2017-06-10T19_19_40_198Z-debug.log


```
**How do I fix this? Where are the credentials supposed to go? What am I doing wrong here?**

**Comment by Atlas7** [comment]
Try this - essentially create two files on your local machine (one for credentials and one for config). The article shows where to store the two files on Windows/Mac/Linux: http://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html

**Comment by talk2camden** [comment]
That didn't work. I still get the same exact message even with the addition of the config file. What's going on?

**Comment by talk2camden** [comment]
Hey this might work! Here's my fix: DON'T PUT ANYTHING under "AWS Profile" in the tool! It will screw it all up. (Not cool)
