### ISSUE TITLE
Does not run "npm start"

### ISSUE THREAD

**Issue by kleber-maia** [alexa/interactive-adventure-game-tool#42]
> interactive-adventure-game-tool@1.0.0 start /Users/klebermaia/Projects/Alexa/interactive-adventure-game-tool
> ./node_modules/gulp/bin/gulp.js

/Users/klebermaia/Projects/Alexa/interactive-adventure-game-tool/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/klebermaia/Projects/Alexa/interactive-adventure-game-tool/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/klebermaia/Projects/Alexa/interactive-adventure-game-tool/gulpfile.js:1:85)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/Users/klebermaia/Projects/Alexa/interactive-adventure-game-tool/node_modules/gulp/bin/gulp.js:116:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interactive-adventure-game-tool@1.0.0 start: `./node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interactive-adventure-game-tool@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/klebermaia/.npm/_logs/2017-07-23T02_01_35_611Z-debug.log

**Comment by jordan-mGH** [comment]
I'm having this same error, trying to follow along with a tutorial that uses this, I have run into this issue.

**Comment by philmcneely** [comment]
in package.json, I updated "require-dir": "^0.2.0" to "require-dir": "^0.3.2",

using node v8.2.1 and npm 5.3.0
not tested with any other versions, hence no PR submitted
