### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by robt79** [alexa/interactive-adventure-game-tool#47]
ode_modules/aws-sdk/lib/request.js:30
            throw err;
            ^

Error: Missing credentials in config
    at Request.callListeners (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/roberttorres/interactive-adventure-game-tool/node_modules/gulp-awslambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the interactive-adventure-game-tool@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roberttorres/.npm/_logs/2017-08-06T06_20_16_619Z-debug.log

Anyone figure out how to fix this?

**Comment by Hopet** [comment]
I had this same issue - running npm install again and adding github credentials when asked fixed this for me
