### ISSUE TITLE
Beginner Issues :/

### ISSUE THREAD

**Issue by jmloredo** [alexa/interactive-adventure-game-tool#52]
Hi all, trying my best to get everything set up. Part I of the tutorial was a breeze. Part II - setting up your computer - I've been lost in the woods for about 2 days now... I keep receiving this error when trying to install NPM after cloning the git. If i try to start I have occasionally been able to get a browser window to show up, but empty screen. This is what showed up in terminal: 

Jes-MacBook-Pro:~ jloredo$     git clone  https://github.com/alexa/interactive-adventure-game-tool.git
Cloning into 'interactive-adventure-game-tool'...
remote: Counting objects: 128, done.
remote: Total 128 (delta 0), reused 0 (delta 0), pack-reused 128
Receiving objects: 100% (128/128), 187.19 KiB | 558.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.

Jes-MacBook-Pro:~ jloredo$ npm install
npm ERR! file /Users/jloredo/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token 
npm ERR!  in JSON at position 1058 while parsing '{
npm ERR!   "name": "interactive-adventure-game-'
npm ERR! File: /Users/jloredo/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jloredo/.npm/_logs/2017-10-13T02_02_45_338Z-debug.log
Jes-MacBook-Pro:~ jloredo$ 

Any ideas would be appreciated, thanks! :)

**Comment by appolonia** [comment]
Hello, I'm also having real trouble in getting the tool to open up. Any help would be much appreciated!

->  npm start

> interactive-adventure-game-tool@1.0.0 start /Users/pebblesandprincess/interactive-adventure-game-tool
> node node_modules/gulp/bin/gulp.js

/Users/pebblesandprincess/interactive-adventure-game-tool/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/pebblesandprincess/interactive-adventure-game-tool/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/pebblesandprincess/interactive-adventure-game-tool/gulpfile.js:1:85)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/Users/pebblesandprincess/interactive-adventure-game-tool/node_modules/gulp/bin/gulp.js:116:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interactive-adventure-game-tool@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pebblesandprincess/.npm/_logs/2017-12-28T08_15_54_362Z-debug.log
PebblesesssiMac:interactive-adventure-game-tool pebblesandprincess$
