### ISSUE TITLE
npm start issue in Windows Machine

### ISSUE THREAD

**Issue by Veiam** [alexa/interactive-adventure-game-tool#54]
This is the error log I get when I do npm start

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\skyip\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle interactive-adventure-game-tool@1.0.0~prestart: interactive-adventure-game-tool@1.0.0
6 info lifecycle interactive-adventure-game-tool@1.0.0~start: interactive-adventure-game-tool@1.0.0
7 verbose lifecycle interactive-adventure-game-tool@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle interactive-adventure-game-tool@1.0.0~start: PATH: C:\Users\skyip\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\skyip\Documents\GitHub\interactive-adventure-game-tool\interactive-adventure-game-tool\node_modules\.bin;C:\Users\skyip\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Amazon\AWSCLI\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Users\skyip\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\skyip\skyip\AppData\Local\Programs\Python\Python36\;C:\Users\skyip\AppData\Local\Microsoft\WindowsApps;C:\Users\skyip\AppData\Local\Microsoft\WindowsApps;C:\Users\skyip\AppData\Roaming\npm;C:\Users\skyip\AppData\Local\GitHubDesktop\bin;C:\Users\skyip\AppData\Local\atom\bin
9 verbose lifecycle interactive-adventure-game-tool@1.0.0~start: CWD: C:\Users\skyip\Documents\GitHub\interactive-adventure-game-tool\interactive-adventure-game-tool
10 silly lifecycle interactive-adventure-game-tool@1.0.0~start: Args: [ '/d /s /c', 'node node_modules/gulp/bin/gulp.js' ]
11 silly lifecycle interactive-adventure-game-tool@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle interactive-adventure-game-tool@1.0.0~start: Failed to exec start script
13 verbose stack Error: interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\skyip\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\skyip\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid interactive-adventure-game-tool@1.0.0
15 verbose cwd C:\Users\skyip\Documents\GitHub\interactive-adventure-game-tool\interactive-adventure-game-tool
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\skyip\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
22 error Exit status 1
23 error Failed at the interactive-adventure-game-tool@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any help will be appreciated.

Also this is what I get after I do npm install

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN interactive-adventure-game-tool@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Web-Cam** [comment]
I created a pull request with windows instructions, but here they are. 
```
Step 1 : Create a file in your home directory (usually your name) named .aws
In order to do this on windows, simply crate a new folder with the name .aws.
Step 2 : Create a file in that folder with the name credentials.file using notepad
Inside include this code
[default]
aws_access_key_id = [KEY FROM AWS]
aws_secret_access_key = [SECRET KEY FROM AWS]

	Replacing those codes with the ones found in AWS console This you get by logging into 
IAM (http://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html)

step 3:  Install node from https://nodejs.org/en/
step 4:Install NPM from https://www.npmjs.com/
step 5 : Install git https://git-scm.com/downloads

Step 6: Run git clone https://github.com/alexa/interactive-adventure-game-tool.git in command prompt
Step 7: CD to that drive it will be in C:\Users\NAME\interactive-adventure-game-tool replacing name with your home directory name

so CD C:\Users\name\interactive-adventure-game-tool in command prompt.

Step 8 : Type npm install and wait, it will take a while
Step 9 : Npm Start and then allow, it should open.

```
Hope this helps! i saw this guide and couldn't believe they only made it for macs and nobody posted windows instructions!

**Comment by schwarma23** [comment]
Hi - I needed to edit the package.json in the "interactive-adventure-game-tool" folder to bump the version of require-dir from 0.2.0 to 0.3.2.  You cannot just edit the file with an editor else the install will fail.
I used www.jsoneditoronline.org and re-saved the edited version.  Look for line 38 ("require-dir": "^0.3.2",)
That got me past your error but then I still had a Python error (installed Python 2.7.X) after that and an MS Framework 4.0 (my computer) vs 2.0 (after that (which I haven't yet resolved).

I hope this helps!

**Comment by AlexanderGorny** [comment]
I have had a problem with python and just installed python 2.7 frome here and it finally worked...but the fonts doesnt seem to fit, so it looks a little bit different from running on the mac
