### ISSUE TITLE
Error During NPM Start

### ISSUE THREAD

**Issue by TheCatster** [alexa/interactive-adventure-game-tool#59]
I have reviewed all other posts, and none seem to help. I keep getting this result:
`
> interactive-adventure-game-tool@1.0.0 start /Users/make717/interactive-adventure-game-tool
> node node_modules/gulp/bin/gulp.js

/Users/make717/interactive-adventure-game-tool/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/make717/interactive-adventure-game-tool/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/make717/interactive-adventure-game-tool/gulpfile.js:1:85)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/Users/make717/interactive-adventure-game-tool/node_modules/gulp/bin/gulp.js:116:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interactive-adventure-game-tool@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/make717/.npm/_logs/2018-01-22T18_33_44_967Z-debug.log`

Any Ideas?

**Comment by TheCatster** [comment]
I updated Node to the latest version (9.something) and am now getting this error:
`
> interactive-adventure-game-tool@1.0.0 start /Users/make717/interactive-adventure-game-tool
> node node_modules/gulp/bin/gulp.js

[13:38:24] Using gulpfile ~/interactive-adventure-game-tool/gulpfile.js
[13:38:24] Starting 'default'...
[13:38:24] Starting 'styles'...
[13:38:24] 'styles' errored after 104 ms
[13:38:24] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/make717/interactive-adventure-game-tool/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/make717/interactive-adventure-game-tool/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/make717/interactive-adventure-game-tool/node_modules/gulp-sass/index.js:187:21)
[13:38:24] Error in plugin 'run-sequence(styles)'
Message:
    Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
Stack:
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/make717/interactive-adventure-game-tool/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/make717/interactive-adventure-game-tool/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/make717/interactive-adventure-game-tool/node_modules/gulp-sass/index.js:187:21)
[13:38:24] Finished 'default' after 109 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interactive-adventure-game-tool@1.0.0 start: `node node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interactive-adventure-game-tool@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/make717/.npm/_logs/2018-01-22T18_38_24_204Z-debug.log`

**Comment by jess0407** [comment]
same here
